#!/bin/bash

if [[ $# -lt 1 ]]; then
  echo "You're WRONG!"
  exit 1
fi

GITFLOW_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

SUBCOMMAND="$1";

function run_bash_command {
  local SUBCOMMAND=$1; shift
  local SUBACTION=$1; shift

  CMD_SCRIPT="git-flow2-${SUBCOMMAND}-${SUBACTION}"

  if [[ "${SUBACTION}" == "-h" ]]; then
    echo "help is TODO"
    exit 0
  fi
  
  if [[ ! -x "${GITFLOW_DIR}/${CMD_SCRIPT}" ]]; then
    echo "Git flow command '${SUBCOMMAND} ${SUBACTION}' not found."
    exit 1
  fi

  ${GITFLOW_DIR}/${CMD_SCRIPT} $@
}

case $SUBCOMMAND in
  release) git-trunk $@; exit $? ;;
  story) git-trunk $@; exit $? ;;
  *) run_bash_command $@
esac

