#!/bin/bash

GITFLOW_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

function cmd_start {
  ${GITFLOW_DIR}/git-flow2-feature-start `pwd` 
}

function cmd_finish {
  ${GITFLOW_DIR}/git-flow2-feature-finish `pwd` 
}
